### ISSUE TITLE
Support Java 7

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#12]
Originally, we chose to convert to Java 8, because it appeared to be stable enough, and the `lambda` feature seemed convenient.

However, the reality is different now:
  * It is hard to find openjdk-8 builds on all platforms. This hampers `https` support because Oracle builds don't enable advanced ciphers by default. See #11 
  * Checked exceptions make lambdas difficult to use (unlike in Scala). Also may classes don't expose a good functional interface (such as the `Option`) class, hampering the use of lambdas.

Hence, it might be worthwhile to convert code to be Java 7 compatible.

**Comment by vn971** [comment]
Is it still a valid issue, can I change the code by deleting the `@NotNull` annotation from types?..

**Comment by hrj** [comment]
@vn971 Did you delete a comment here?

I think supporting Java 7 is not required / worthwhile anymore. Somethings have changed now:
* Azul Systems has released OpenJDK8 builds on all platforms, under GPL license. They also support strong ciphers (albeit as a separate download).
* The null analysis enabled by Java 8 type annotations is extremely useful.
* Writing functional code using lambdas is a bit cumbersome, but I later learnt that lambdas in Java 8 are more optimal than simple anonymous classes. So there's that.
* We are now using some Java 8 features such as `Base64` class and couple of others.
* Java 7 has reached EOL. Security updates are now guranteed by only a few vendors (like RedHat).

So I think Java 8 is a good target as of today. Closing.

**Comment by hrj** [comment]
To add to the above list, we are using default methods in interfaces (a Java 8 feature).
