### ISSUE TITLE
Menu File -> Open File... should be disabled until it works

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#132]
Clicking on File -> Open File throws an exception because of strict access control. Need to work an access control UI, but until then the menu button can be simply disabled / hidden.

**Comment by hrj** [comment]
The menu entry has been disabled for now.

**Comment by chetankothari** [comment]
@hrj I just checked this and see that the menu item is neither disabled nor hidden. I would be able to do either if required.

**Comment by hrj** [comment]
@chetankothari  good catch! I don't know why I wrote "it has been disabled". :confused: 

Please go ahead and disable it. Note that only `Open File` action needs to be disabled. It can be triggered either through `File menu -> Open -> File...` option or via `Ctrl-O` shortcut.

Thanks!

**Comment by chetankothari** [comment]
@hrj do we have a release branch against which the PR should be raised? I have raised it against `master`. [PR](https://github.com/UprootLabs/gngr/pull/217). Let me know if I have to change that.

**Comment by hrj** [comment]
`master` was the appropriate branch. Currently, whatever is on master branch gets included in the next release (along with some WIP patches).

**Comment by chetankothari** [comment]
Cool.
