### ISSUE TITLE
Support for Mac Os (keyboard command)

### ISSUE THREAD

**Issue by atiqsayyed** [UprootLabs/gngr#156]
Keyboard shortcut for mac doesn't work. example (copy : Ctrl +v instead of:  Command +v)
other shortcuts too..

----

Adding the list by @bogas04:

* [x] **cmd L** for AddressField focus
* [x] **cmd C** for copy
* [x] **cmd u** for page source
* [x] **cmd O** for opening a file
* [x] **cmd W** for closing tab/window
* [x] **cmd left** & **cmd right** for back/forward
* [x] **cmd X** & **cmd V** for cut & paste
* [x] **cmd K** for search
* [ ] **cmd S** for save

-- hrj

**Comment by hrj** [comment]
Thanks for reporting. I don't have a Mac so I wouldn't be able to fix this soon.

But the good news to me is that *something* in gngr does work on Mac OS, for you to notice this :smile:

**Comment by bogas04** [comment]
I have added (https://github.com/UprootLabs/gngr/pull/161) support for cmd L for now, will dig deep and add for all.
@hrj I think we should add a boolean somewhere to detect which OS gngr is running on. 

@atiqsayyed  mind adding following list to your OP?

* [x] **cmd L** for AddressField focus
* [ ] **cmd C**, **cmd X** & **cmd V** for copy cut & paste
* [ ] **cmd O** for opening a file
* [ ] **cmd K** for search
* [ ] **cmd S** for save
* [ ] **cmd [** & **cmd ]** for tab switching (future)
* [ ] ...

**Comment by hrj** [comment]
Oh, just saw this message after posting mine :)

Yes, it would be good add a boolean or enum in `PlatformInit` class.

**Comment by bogas04** [comment]
@hrj  where are all the shortcuts implemented?

**Comment by hrj** [comment]
@bogas04 I don't think there is a single place for all shortcuts. You will need to grep the code.

**Comment by hrj** [comment]
@bogas04 has fixed some of the above listed shortcuts for OSX.

@atiqsayyed can you confirm if those work for you?

**Comment by bogas04** [comment]
CMD + K is dependent on https://github.com/UprootLabs/gngr/issues/158

**Comment by atiqsayyed** [comment]
@hrj @bogas04 
Issues like 
cmd C for copy
cmd V for paste
cmd O for opening file
are not working for Mac OSX. .

Sorry to see this late

**Comment by hrj** [comment]
Hmm, @bogas04 says `cmd C` works for copying. Perhaps it doesn't work for certain websites / situations. Let's try to standardise the test.

* Run gngr and stay on the `about:welcome` page.
* Select `Welcome to gngr` using the mouse / touchpad pointer.
* Press `cmd C` to copy. Check if it worked by pasting in some other application.
* Press `cmd L` in gngr. This should focus the address bar and select the text in it.
* Press `cmd V` to paste `Welcome to gngr` in the address bar.

@atiqsayyed Can you confirm if the above works?

**Comment by bogas04** [comment]
cmd c particularly works for address bar, but not in other textboxes and areas. I tried to find a solution but couldn't find it. Maybe we will have to add eventListeners to every text box that is rendered (Sounds ugly to me)

**Comment by hrj** [comment]
@bogas04 Have a look at this [SO question](http://stackoverflow.com/questions/7252749/how-to-use-command-c-command-v-shortcut-in-mac-to-copy-paste-text).

The accepted answer seems to be a global (application level) solution.

If that answer doesn't work, try changing the relevant code in `HtmlBlockPanel` constructor ( the part where `registerKeyboardAction` is called).

**Comment by atiqsayyed** [comment]
@hrj @bogas04  I can check this coming next week. .

**Comment by bogas04** [comment]
@hrj I don't have permissions to edit the OP, can u please update the list :

* [x] **cmd L** for AddressField focus
* [x] **cmd C** for copy
* [x] **cmd u** for page source
* [x] **cmd O** for opening a file
* [x] **cmd W** for closing tab/window
* [x] **cmd left** & **cmd right** for back/forward
* [x] **cmd K** for search
* [x] **cmd X** & **cmd V** for cut & paste
* [ ] **cmd S** for save
* [ ] ...

**Comment by apicellaj** [comment]
@hrj I'm thinking about implementing **cmd S** but I couldn't find any Save function already present (in Action Pool or elsewhere) so I was curious if you had any idea of how you wanted this feature to be implemented.

**Comment by hrj** [comment]
@bogas04 Updated

@apicellaj Currently, the security policy is very tight in gngr. There is no read permission for anything in the filesystem (except `~/.gngr/*`), let alone write permission. That is why I removed the save feature, IIRC.

I will remove the save feature from the list in this issue. We can add more OS X shortcuts as more features get supported.

.... which means this issue is now completed. Thanks all for the support!
