### ISSUE TITLE
Ctrl-K keyboard shortcut for starting a search doesn't work anymore

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#158]
In `gngr`, you can start a search by typing `?` in the URL bar followed by the search keyword.

There was also a `Ctrl-K` keyboard shortcut to automatically focus the URL bar, and replace its contents with a `?`.

Somehow, this has stopped working or has got disabled. Fixing this should be very easy.

**Comment by bogas04** [comment]
https://github.com/UprootLabs/gngr/pull/164

**Comment by hrj** [comment]
Closed via https://github.com/UprootLabs/gngr/commit/71ab3e345130b97f5dce8c20e8a420565b7cf8f4

**Comment by atiqsayyed** [comment]
I'll confirm thus
