### ISSUE TITLE
Ctrl-L doesn't select the content of the address bar

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#159]
The keyboard shortcut Ctrl-L properly puts the focus into the address bar. It however doesn't select the text automatically.

Selecting automatically will allow the user to type a new URL immediately.

**Comment by bogas04** [comment]
I'm willing to take this up! Can you tell me which part of code deals with shortcut event listeners ?

**Comment by hrj** [comment]
@bogas04  Cool!

There is a class called `AddressField` and an instance of this is managed by `ComponentSource`.

I am about to travel, so can't find the exact place where the short cut is used right now. I will be back after a couple of hours. If you can't find the relevant part in the meanwhile, let me know.

**Comment by hrj** [comment]
Found it! In `AddressField` class, there is this code:
```
    getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ctrl L"), "edit URL");
    getActionMap().put("edit URL", new AbstractAction() {

      public void actionPerformed(final ActionEvent e) {
        requestFocus();
      }
    });
```

It is currently only requesting focus. You need to also make it select the text.
