### ISSUE TITLE
ACID 1 : Wrong color for toggle

### ISSUE THREAD

**Issue by bogas04** [UprootLabs/gngr#162]
gngr

![screen shot 2015-09-15 at 1 27 55 am](https://cloud.githubusercontent.com/assets/6177621/9860333/19177f56-5b49-11e5-9682-c46f4e0aca73.png)

firefox

![screen shot 2015-09-15 at 1 24 41 am](https://cloud.githubusercontent.com/assets/6177621/9860252/a15708c4-5b48-11e5-98d7-d9c2272f525e.png) |

**Comment by hrj** [comment]
Yup, that's a known one, though I forget the details right now. Will update later.

PS. I have changed the formatting of your comment @bogas04. The second screenshot was overflowing my screen.

**Comment by bogas04** [comment]
@hrj my bad!

**Comment by hrj** [comment]
Btw, apart from the ACID tests, there is a complete CSS 2.1 test suite available from w3c, and we are in the process of automating those tests.

The ACID tests are hard to debug because they cram lots of features into a single test. We need to address the normal tests first.
