### ISSUE TITLE
Strings which don't match the URL pattern should be searched when typed in AddressField

### ISSUE THREAD

**Issue by bogas04** [UprootLabs/gngr#165]
Modern browsers allow you to enter non-URL strings to the addressbar which get searched using default search engine.

Since an exception is thrown I believe we aren't processing the string before making HTTP request. 

![screen shot 2015-09-16 at 1 14 42 am](https://cloud.githubusercontent.com/assets/6177621/9888021/58b72162-5c10-11e5-8fd6-76064eee47de.png)

**Comment by hrj** [comment]
Yes, we haven't implemented this at the moment.

It would be nice if the drop down suggestions included an option to search for the string, in addition to the history suggestions.
