### ISSUE TITLE
Support for auto-completing URL domain shortcuts

### ISSUE THREAD

**Issue by bogas04** [UprootLabs/gngr#166]
For example typing hostname without domain and using one of following shortcuts should expand it correctly.
```google``` + ```Ctrl+Enter``` → ```google.com```

Some commonly known shortcuts
* [ ] `Ctrl+Enter` for `.com`
* [ ] `Ctrl+Shift+Enter` for `.org`

**Comment by hrj** [comment]
This might have been a good idea at an earlier time when `.com` and `.org` were the most common domains. But these days, there are many top level domains in common use. To me, it doesn't make sense to favor a subset of domains.

**Comment by hrj** [comment]
Did some quick research. According to [this page](http://www.registrarstats.com/TLDDomainCounts.aspx), `.com` registrations are way higher than the others. The surprising thing is `.net` is more common than `.org`.

Also, there is huge growth in the new vanity domains like `.xyz`, and I think that will be the trend going forward.

Unless there is good reason to re-consider, I am going to decline this idea for now. Sorry!
