### ISSUE TITLE
width="100px" doesn't work for img elements

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#167]
This works:

```
<img src="..." width="100" />
```

But this doesn't
```
<img src="..." width="100px" />
```

**Comment by atiqsayyed** [comment]
I'm picking this up.  .

**Comment by hrj** [comment]
@atiqsayyed great! Let me know if the description is not sufficient in any issue. I sometimes just write the issue description in a hurry. Will come online after some time.

**Comment by atiqsayyed** [comment]
By going through the code, i found that It can be the case with any attribute, not only just width. . 
Should i do a generic fix?? (this can affect other elements as well) 
Or should i fix it only for Image height and width.. which will solve the above issue?

**Comment by hrj** [comment]
@atiqsayyed Generic fix is better. You need to read the [CSS specs](http://www.w3.org/Style/CSS/) to ensure that other elements are not adversely affected. (Fortunately we have the automated tests now, as a safety net). [MDN](https://developer.mozilla.org/en-US/) is also a good resource.

**Comment by hrj** [comment]
@atiqsayyed If you find that the CSS spec is silent about something, we can follow the example of other browsers for that particular thing. The reference browser we have chosen is Firefox (because it tends to be more consistent).
