### ISSUE TITLE
not a gngr issue, bug blog links on the site

### ISSUE THREAD

**Issue by vn971** [UprootLabs/gngr#177]
gngr-s RSS feed https://blog.gngr.info/feed.xml generates links like
`https://blog.gngr.infov03.10.html/`
whereas it should be `***.gngr.info/***`  (note the slash). If it's easy to fix, please fix it.
Thanks.

**Comment by hrj** [comment]
Thanks for reporting. I think this might be a bug in your feed reader, but nevertheless I have pushed a workaround. Can you check again?

---
The details are: The link was a relative address. It was simply of the form `v03.10.html` and the RSS reader is supposed to create a URL based on the feed's base URL. It works fine with the RSS feed readers that I tested. However, as a workaround, I have made it an absolute path, of the form `/v03.10.html`.

Closing this assuming it's fixed.

**Comment by vn971** [comment]
Thanks! Yup, it got fixed in my reader.
