### ISSUE TITLE
Maven or gradle support?

### ISSUE THREAD

**Issue by linkerlin** [UprootLabs/gngr#191]
For better integration with Intellij idea.

**Comment by hrj** [comment]
Have you tried using the [ant support](https://www.jetbrains.com/idea/help/ant.html) in IntelliJ? We now have an ant build file, located at `src/build.xml`. I don't use IntelliJ much; @atiqsayyed might have some inputs.

If that doesn't work, then `maven` support would be also welcome.

**Comment by atiqsayyed** [comment]
It works in Intellij, I've been using it in intellij. .  You just have to import the build.xml file your project

**Comment by hrj** [comment]
Thanks @atiqsayyed 

@linkerlin Closing this because `ant` build is sufficient. If you face any problem, feel free to re-open the issue.
