### ISSUE TITLE
Switch to Loboevolution

### ISSUE THREAD

**Issue by securenamesecure** [UprootLabs/gngr#230]
I think we could switch to Loboevolution for more security because Lobo Browser seems to be not more continued 
Loboevolution: https://github.com/oswetto/Loboevolution

**Comment by hrj** [comment]
Problem is that `gngr` and `Loboevolution` have both diverged in their code base and each have different focus. `gngr` is focussed on security while `Loboevolution` seems to be focussed on features.

One big example of code divergence: `gngr` uses a different library for CSS parsing called `jstyleparser`, while `Loboevolution` continues with `cssparser`.

**Comment by hrj** [comment]
> I think we could switch to Loboevolution for more security because Lobo Browser seems to be not more continued

Btw, gngr is not dependent on LoboBrowser being continued. It was based on LoboBrowser, but has diverged quite a lot now. Just like LoboEvolution.
