### ISSUE TITLE
0.3.15 is old version?!

### ISSUE THREAD

**Issue by za3ter2p** [UprootLabs/gngr#257]
I have downloaded gngr browser which is presented here: 

https://gngr.info/download.html

but when i run: 

java -jar gngr-0.3.15.jar

Then a pop-up show up telling this is the old version and i need to check for the newer version, but where is that?

**Comment by hrj** [comment]
That nag screen is to prevent users being stuck on an old version _in case_ there is a new version released. But there hasn't been a new version recently, so you can ignore the nag dialog for now.

That said, we might soon start making regular releases again, so do subscribe to our blog's RSS feed, or click on Github Watch.

Sorry for the misunderstanding.
