### ISSUE TITLE
 Exception: java.io.IOException 

### ISSUE THREAD

**Issue by za3ter2p** [UprootLabs/gngr#258]
Browsing anything will give: 

```
An error occurred trying to process a request. 
 Exception: 
 java.io.IOException 
 Meaning 
 Indicates an Input/Output error has occurred. This is typically due to a network connection that cannot be establised or one that has failed, but it can also mean that a file could not be accessed or found. 
 Message: 
 Unexpected response code for CONNECT: 503 
```

**Comment by hrj** [comment]
It works fine for me. Can you tell me:

1. output of `java -version`
2. url of a website that fails
3. which OS (although our code is platform independent, CA certificates are usually provided by the OS to Java)

**Comment by za3ter2p** [comment]
1.

user@host:~$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed
mode, sharing)

2. any website no specific , e.g duckduckgo

3. Debian 10 Buster

hrj:
> It works fine for me. Can you tell me:
> 
> 1. output of `java -version`
> 2. url of a website that fails
> 3. which OS (although our code is platform independent, CA certificates are usually provided by the OS to Java)
>

**Comment by hrj** [comment]
I faced a similar problem on a fresh install of Debian 10 just two days back.

Make sure these two packages are installed `ca-certificates` and `ca-certificates-java`.
Then, try running `update-ca-certificates`.

You can test if your setup is working by `wget -O/dev/null https://duckduckgo.com`.
And with `jshell checkGet.jshell`, where `checkGet.jshell` is [this script](https://gist.github.com/hrj/0d4f94dc9b2091dca1fb1358728a6d56).

**Comment by za3ter2p** [comment]
Ok i reinstall it and it worked , the issue is if you modify the
connection within the browser by adding lets say localhost or 127.0.0.1
, port xxxx it wont connect.

you can try that for e.g with I2P once running it, you can change
browser connection to 127.0.0.1 port 4444 (for browsing .i2p)

and to reach its interface its on 127.0.0.1:7657 (this as well wont show
up in the browser)

So we have 2 issues:

- Doesnt connect when modifying connection type
- Doesnt connect to localhost:port

**Comment by hrj** [comment]
Can you try with a simple server such as `python -m SimpleHTTPServer` ?

We test all the time with localhost with different ports, both interactively and through CI.

If the problem is specific to i2p let's track it under #255.

**Comment by za3ter2p** [comment]
> python -m SimpleHTTPServer

user@host:~$ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 610, in test
    httpd.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
KeyboardInterrupt

> If the problem is specific to i2p let's track it under #255.

I figured out what was the problem, i should Tick "Bypass proxy for
localhost addresses" otherwise it will show that error which i dont
understand what is going on.

Feel free to close this ticket.
