### ISSUE TITLE
ant or maven build scripts + Continuous integration

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#6]

**Comment by gim-** [comment]
That would be great. At this moment I have no idea how to build this, there are no build instructions and dependency list.

**Comment by hrj** [comment]
Yeah, I will tackle this soon after 0.4 release.

**Comment by hrj** [comment]
@gim- For development, you can use [this guide](https://github.com/UprootLabs/gngr/wiki/Developer-Setup). It requires Eclipse at the moment.

**Comment by hrj** [comment]
A guideline for anyone who would like to take this up:

When you open the project in Eclipse, you will see a couple of modules: `HTML_Renderer`, `Platform_Core`, etc. These modules need to be built individually into separate jars. There are compile time dependencies between the modules, which can be observed through the Eclipse build path for each module. There also dependencies on external jars, which are all kept inside the `XAMJ_Build/ext` folder.

After compiling, it should be possible to run the browser by specifying all the jars on the classpath, and specifying this entry point: `org.lobobrowser.main.EntryPoint`.

**Comment by atiqsayyed** [comment]
I'm picking this up...
I'll use maven for internal and external dependency management between modules...
Will keep everyone posted on the status

**Comment by hrj** [comment]
@atiqsayyed I just discovered that Eclipse has an option to create an `ant` build file automatically. See [this thread](https://www.reddit.com/r/eclipse/comments/3k3ggt/eclipse_ant/).

However, Eclipse creates separate ant build files for each sub-project. It would be nice to take these files as a starting point and build a single build file out of them.

**Comment by atiqsayyed** [comment]
@hrj I've seen that... I'm trying to integrate the build files which are generated via eclipse... 
will update it

**Comment by vn971** [comment]
I seem to be a bit late on this, but yes, a Maven/SBT/Gradle description would be very helpful. As a start:

* the project could be tested on any platform, including Jenkins/Travis.
* the project-s source repo (git) could be stripped of from huge binaries (*.jar files like for h2)
* you could work from any IDE (e.g. emacs or intellij-idea)
* I seem late on this, but if we'd chose SBT, we could have incremental compilation (that means fast compilation), incremental tests and even incremental run. Like you edit the source and save, and if it compiles, the previous instance of the browser can be killed and a new one started. Not useful in all situations, but very useful in some. Most often I just re-run tests when sources change.

**Comment by hrj** [comment]
You aren't late; nothing's finalised yet :)

SBT is familiar & fine with us.

For dependencies, I would prefer a checksumed download. So far I have not seen a way to do that in sbt / maven.

@atiqsayyed isn't working on this right now, so feel free to pick it up.

**Comment by vn971** [comment]
@hrj OK, cool.

I now spent about 1 hour investigating verification methods in java world. Seems like there are no open solutions for that. The only things I found is a proprietary proxy "Nexus Pro" and manual GPG verification.

I will use checked-in artifacts while trying to migrate to SBT. (After manual verification, of course.)

---------------
_unnecessary to read_. Alternative I know about:
the project could open up a separate git repository and store raw artifacts in it. Then, use this git repo inside the main repo as a "git submodule". This way, the main repo can live without the jar-s at all, but be able to specify the exact dependencies. Anyway, I'm not suggesting this yet because of the added complexity.

**Comment by hrj** [comment]
About `ant`: There is a [discussion on SO](http://stackoverflow.com/questions/819568/pass-ant-target-to-multiple-build-xml-files-in-subdirectories) about integrating different ant build files into a master ant file. There is one quick solution, and one of the comments links to a [different soution](http://www.exubero.com/ant/dependencies.html) which might be suitable in the long run.

**Comment by hrj** [comment]
All,

I got the ant file building successfully. It turns out that Eclipse is pretty smart in exporting the ant file; all dependencies and launch configurations are automatically exported.

So just running `ant ant -f src/Platform_Core/build.xml EntryPoint`will now compile and execute `gngr`. :clap: 

For convenience, I have added a `src/build.xml` which invokes the build in sub-projects, but it really isn't required.

Using the ant build file, I have also enabled `travis ci` for this repo! Currently it just checks whether everything compiles or not.

Further things to do in the automated build:
* Enable testing using grinder. 
* Enable testing using `web-platform-tests`.
* Enable packaging of jar file.

**Comment by hrj** [comment]
I have created separate issues for future work:

* automated grinder tests: https://github.com/UprootLabs/gngr/issues/180
* automated webplatform tests: https://github.com/UprootLabs/gngr/issues/182
* automated packaging of jar: https://github.com/UprootLabs/gngr/issues/183

**Comment by hrj** [comment]
regarding verification of binaries: gradle has a solution called [witness](https://github.com/WhisperSystems/gradle-witness). I wish ant / maven / sbt had something similar.
