### ISSUE TITLE
Default font: serif or san-serif

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#78]
We are currently using `sans-serif` for default font, while other browsers use `serif`. Need to decide on one.

**Comment by Nidish93** [comment]
Hello, the top 3 safe web fonts that I found out are: 
1.	Arial (Sans-serif) 
2.	Times New Roman (Serif)
3.	Courier New (Mono)

When a web page loads, a browser will be told to write text onto the screen using a specified font that is stored directly on a local directory, from fonts already installed on a computer. If a user does not have the specified font installed, it won’t show up and will instead see a default font that might not look good. Hence, fonts that come bundled in the various OS are known as “Web-safe”.
The two widely OS, Windows and Mac OS only share 10 ten fonts that overlap as illustrated in this [picture] (http://imgur.com/a/EuQ57). Also by going through the popularity of fonts used:
(i)	by both OS, I found out that Arial, Times New Roman and Courier New came out on top. [Picture here!] (http://imgur.com/a/MRLv2) (found on www.cssfontstack.com)
(ii)	by browsers such as Firefox, Chrome and Safari, the same [results] (http://imgur.com/a/vzBaF) for windows. (found on www.granneman.com)

If it is a case of serif vs non-serif, I would personally like the browser to stay on the non-serif font, specifically Arial. A couple of good articles make some good points that Arial is the most suited for the web and computer screen. ([Article 1] (http://www.awaionline.com/2011/10/the-best-fonts-to-use-in-print-online-and-email/) & [Article 2] (http://www.webdesignerdepot.com/2013/03/serif-vs-sans-the-final-battle/)). 

As a side note: All the popular browsers use font stacking, that is a browser will store fonts as first font choice, second font choice etc. This is illustrated in the following [picture] (http://imgur.com/a/vzBaF). This will essentially ensure that a browser will always display an acceptable font. To maintain consistency, gngr should follow the same guidelines.( [Article] (http://www.practicalecommerce.com/articles/3080-How-Browsers-Manage-Fonts) on how Browsers Manage Fonts).

**Comment by hrj** [comment]
@Nidish93 Thank you for that detailed comment.

There are two separate topics getting intertwined here:
* "serif", "sans-serif", "mono" are virtual fonts which get mapped to actual fonts, based on system and user preferences.
* when an element's computed `font-family` is not defined, what should it default to?

This issue is about the second topic. Which should be the default virtual font: `serif` or `sans-serif` when an element doesn't have one specified in CSS.

> If it is a case of serif vs non-serif, I would personally like the browser to stay on the non-serif font, specifically Arial. A couple of good articles make some good points that Arial is the most suited for the web and computer screen. (Article 1 & Article 2).

Thanks for voicing your preference and linking to those articles. Those articles justify why "sans-serif" is a good default option for screen.

If you (or anyone) can find a specification that says browsers *should* default to "serif", then please let me know. Otherwise, to the best of my knowledge, "sans-serif" is a good default and this issue can be closed.

**Comment by hrj** [comment]
From [the spec](https://www.w3.org/TR/CSS2/fonts.html#propdef-font-family) it is clear that the `initial` value of `font-family` is entirely upto the User-Agent.

So, we can continue using `sans-serif` in `gngr` and thanks to @Nidish93, we have links to good articles about why `sans-serif` is more readable on screens, even for body-text.
