### ISSUE TITLE
h2 DB access exception on Windows

### ISSUE THREAD

**Issue by vit1251** [UprootLabs/gngr#83]
Figure 1. With Exception trace back

![Figure 1](http://oi61.tinypic.com/2rml6bp.jpg)

P.S. Please use System.err.println(traceback) it can capture and make easy help catch values.

**Comment by vit1251** [comment]
Also can't catch bottom screen - monitor is over ;) But about Alt + PrtScn in that moment I not remember.

**Comment by hrj** [comment]
Thanks for reporting but I can't reproduce this error. However, we have discussed a related problem with h2 database developers and will be following their suggestions in the next release.

Also, the exception is printed on stderr if you pass `-debug` command line option to gngr like this:
```
java -jar gngr-v0-3-5.jar -debug
```

**Comment by vit1251** [comment]
You may write error log into file. It very usable solution.

**Comment by hrj** [comment]
Hey @vit1251  , this error might be related to #92 which is now fixed.

Please check with version 0.3.6 and re-open this bug if required.

Logging to file; good idea; though not a priority right now.
