### ISSUE TITLE
Submit Cobra rendering changes upstream please

### ISSUE THREAD

**Issue by xaoseric** [UprootLabs/gngr#87]
Hi there,
Please submit any changes you make to cobra upstream. Also, please be aware that we are working on updating our Cobra rendering engine which may make any changes you did unstable. You can submit changes at https://github.com/lobobrowser/Cobra

Thank you in advanced :)

**Comment by hrj** [comment]
Hi,

Thanks for looking here and pointing us to your repository.

We have diverged quite a bit from the original Cobra code. For example, we now use jStyleParser for CSS parsing and analysis because we found the the CSSParser code to be very brittle.

Are you okay with this direction? It would be good to know more about your plans and how you are related to the Lobo project.

cheers!

**Comment by xaoseric** [comment]
Hi there,
Yes I am ok with this direction, I was actually looking at replacing the CSSParser code. The html rendering engine itself currently uses w3c html 4 standards, we plan to update that to HTML 5 standards. I am the lead developer of the Lobo project. I recently talked with the former developer of the Lobo project and got the go ahead from them to take over the project.

**Comment by xaoseric** [comment]
Also, the browser theme will be getting an over hall, and there will be a proper search bar implemented along with a proper default search engine - most like the default search engine will be bing

**Comment by xaoseric** [comment]
The theme rewrite will use javafx, and will feature a light theme by default

**Comment by hrj** [comment]
> I recently talked with the former developer of the Lobo project and got the go ahead from them to take over the project.

Can you please point me to a public discussion about it? If it doesn't exist, it would be better to initiate one. Thanks.

**Comment by xaoseric** [comment]
Here you go:
http://sourceforge.net/p/forge/site-support/9506/

As you can see, the former admin added me as a project admin.  Also, you can see by the screenshot that I have admin access.

![c1dlbw9](https://cloud.githubusercontent.com/assets/643544/5903979/ff108a0a-a552-11e4-95fd-98308f49cad1.png)

**Comment by hrj** [comment]
Thanks very much for your response.

Sorry for my ignorance but that seems to be someone from the SF support staff who have granted you admin rights. I would like to know a few more things.

  * Were you able to contact any of the original contributors of the Lobo project and did you get their permission publicly?
  * Are you also in control of http://lobobrowser.org/ ?

These have implications for copyright.

**Comment by hrj** [comment]
@xaoseric,

Submitting patches seems difficult at this moment. There's one year's worth of divergence in the code and our package hierarchies seem completely different.

You have also changed the license from GPL to MIT.

I am not able to wrap my mind around all this. I guess it would have been easier if we had known of each other's efforts and co-ordinated it from the beginning.

Closing this issue for now. If you would like to take it up, feel free to re-open the issue.

**Comment by xaoseric** [comment]
As we have changed our package hierarchies, I will be making the changes accordingly to the gngr code as well for you and submit them when that is done. We do have official docs we are working on for the cobra engine at http://docs.lobobrowser.org, the repository for that is located at https://github.com/lobobrowser/docs.lobobrowser.org

**Comment by xaoseric** [comment]
The base of the browser engine codenamed Cobra can be found in this repository: https://github.com/lobobrowser/Cobra/tree/master/src/com/lobobrowser/cobra

Similar to how Mozilla uses their xul and gecko rendering, Cobra will be the rendering engine for Lobo Browser that other java browsers can be based upon.
