### ISSUE TITLE
gngr v0.3.5 throws exception when first run on windows

### ISSUE THREAD

**Issue by xaoseric** [UprootLabs/gngr#92]
![gngrerror](https://cloud.githubusercontent.com/assets/643544/5944464/20500184-a6f5-11e4-9f66-7319d2ab8adb.PNG)
Not sure if anyone else has noticed this, but gngr is not creating the .gngr folder. I notice that gngr v0.3.5 will only work after running gngrv0.3.1.

**Comment by hrj** [comment]
Oh, thanks for reporting, @xaoseric 

We don't use Windows much, hence missed it. Will try to analyse and fix this soon.

**Comment by hrj** [comment]
The `.gngr` folder was being created. But the permissions were not set correctly for Windows. h2 uses different paths on Windows and hence the problem was not detected. It worked fine in earlier releases, probably because h2 permissions were slightly different.

Fixed in version 0.3.6
