### ISSUE TITLE
Support for more border styles: double, groove, ridge, inset, outset

### ISSUE THREAD

**Issue by hrj** [UprootLabs/gngr#98]

**Comment by hrj** [comment]
[Test case](https://uprootlabs.github.io/gngrTestCases/test-case/i98/)

**Comment by hrj** [comment]
Was implemented in PR #104 

Thanks @PayalGodse for your contribution. :+1: 

Let me know if there was something pending. Closing tentatively.

**Comment by PayalGodse** [comment]
There was some optimisation to be done considering the corners of borders.
and some cleaning of code...But main functionality is done.

Hope to contribute more in future :)
